name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'ubuntu-22.04' ]
        ruby-version: ['3.1', '3.2', '3.3']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
  lint:
    strategy:
      matrix:
        os: [ 'ubuntu-22.04' ]
        ruby-version: ['3.3']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Rubocop
      run: bundle exec rubocop
